# PANDAS

### Pandas is a Python library used to read, clean, organize, and analyze data. It is widely used in data analytics. Pandas will support two data structures: 1.series       2.data frame

### 1.Setup and Import

In [1]:
import pandas as pd
import numpy as np

In [3]:
pd.__version__

'2.3.3'

### Creating Series & DataFrames

#### pd.series() ----> One-dimensional data, like a single column

In [7]:
s=pd.Series([10,20,30])
s

0    10
1    20
2    30
dtype: int64

In [9]:
s=pd.Series([10,20,30], index=['a','b','c'],name='values')
s

a    10
b    20
c    30
Name: values, dtype: int64

#### pd.DataFrame()----> Two-dimensional data arranged in rows and columns, like an Excel table

In [2]:
df=pd.DataFrame({
    'name':['Alice','Bob','Charlie','David'],
    'age':[25,30,35,40],
    'city':['NY','LA','SF','NY']
})
df

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [11]:
#pd.DataFrame() from a list of dicts
pd.DataFrame([{'a':1,'b':2},{'a':3,'b':4}])

   a  b
0  1  2
1  3  4

In [12]:
#pd.DataFrame() from a Numpy array
pd.DataFrame(np.arange(6).reshape(2,3),columns=['x','y','z'])

   x  y  z
0  0  1  2
1  3  4  5

### Attributes & Inspection

In [14]:
# .shape----->(rows,columns)
df.shape

(4, 3)

In [16]:
# .columns ----> Column labels
df.columns

Index(['name', 'age', 'city'], dtype='object')

In [17]:
# .index ---> row labels
df.index

RangeIndex(start=0, stop=4, step=1)

In [18]:
#dtypes ---->data types of each column
df.dtypes

name    object
age      int64
city    object
dtype: object

In [19]:
# .values ----> Underlying NumPy array
df.values

array([['Alice', 25, 'NY'],
       ['Bob', 30, 'LA'],
       ['Charlie', 35, 'SF'],
       ['David', 40, 'NY']], dtype=object)

In [20]:
# .size ----> Toltal number of elements
df.size

12

In [22]:
# .head() ----> first n rows  [by defalult we will get first 5 rows]
df.head(2)

    name  age city
0  Alice   25   NY
1    Bob   30   LA

In [23]:
# .tail()----->last n rows     [by defalult we will get last 5 rows]
df.tail(3)

      name  age city
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [24]:
#.info() ----> Summary of DataFrame (dtypes,non-null counts)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      object
 1   age     4 non-null      int64
 2   city    4 non-null      object
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes

In [25]:
# .describe() -----> Brief statistical discription of numeric columns
df.describe()

             age
count   4.000000
mean   32.500000
std     6.454972
min    25.000000
25%    28.750000
50%    32.500000
75%    36.250000
max    40.000000

In [26]:
# .memory_usage() ----> Memory used by each column
df.memory_usage()

Index    132
name      32
age       32
city      32
dtype: int64

### Selection & Indexing    (loc,iloc,at,iat)

In [28]:
df

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [27]:
# .set_index() ----> Set a column as the row index
df.set_index('name',inplace=False)

         age city
name
Alice     25   NY
Bob       30   LA
Charlie   35   SF
David     40   NY

In [29]:
#inplace=False --->this means changes are not stored or did permently
#inplace=true---->this means changes are stored and  did permently

In [30]:
df.set_index('name',inplace=True)

In [31]:
df

         age city
name
Alice     25   NY
Bob       30   LA
Charlie   35   SF
David     40   NY

In [33]:
df

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [5]:
#column Selection ---> Single column returns a Series

In [4]:
df['age']

0    25
1    30
2    35
3    40
Name: age, dtype: int64

In [6]:
#column selection ---> A list of columns returns a DataFrame

In [7]:
df[['name','age']]

      name  age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   40

In [8]:
#   .loc[]----> Select a row by label . 
df.loc[0]

name    Alice
age        25
city       NY
Name: 0, dtype: object

In [9]:
# .loc[] ---> select a scalar value by label
df.loc[0,'age']

np.int64(25)

In [10]:
df.loc[3,'name']

'David'

In [11]:
# .loc[] ---> Select rows and columns by label
df.loc[0:2,['name','age']]

      name  age
0    Alice   25
1      Bob   30
2  Charlie   35

In [12]:
# .iloc[]-----> select a row by integer position
df.iloc[0]

name    Alice
age        25
city       NY
Name: 0, dtype: object

In [14]:
# .iloc[] --->selecta scalar value by integer postion 
df.iloc[0,1]      #0-row and 1-column

np.int64(25)

In [15]:
# .iloc[] ---->select rows and columns by integer postion 
df.iloc[0:2,0:2]

    name  age
0  Alice   25
1    Bob   30

In [16]:
# .at[] ---> Fast scalar access by label
df.at[0,'age']

np.int64(25)

In [17]:
# .iat[] ---> Fast scalar access by integer position
df.iat[0,1]

np.int64(25)

### Filtering & Boolean Indexing

Simple Condition----> filter rows by matching one condtion

In [18]:
df[df['age']> 28]

      name  age city
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

Multiple Condition ---> Combine with & / |

In [19]:
#AND &
df[(df['age'] >25) & (df['city'] == 'NY')]

    name  age city
3  David   40   NY

In [23]:
#OR |
df[(df['city'] =='NY') | (df['name']=='David')]

    name  age city
0  Alice   25   NY
3  David   40   NY

In [25]:
df[(df['city'] =='NY') | (df['name']=='Bob')]

    name  age city
0  Alice   25   NY
1    Bob   30   LA
3  David   40   NY

In [26]:
# .isin()----> Filter rows where a column matches a set of values
df[df['city'].isin(['NY','LA'])]

    name  age city
0  Alice   25   NY
1    Bob   30   LA
3  David   40   NY

.query() ---> Filter using readable string expression

In [28]:
df.query('age > 28 and city =="NY"')

    name  age city
3  David   40   NY

.where()----> Keep matching values, replace other with NAN

In [29]:
df.where(df['age'] > 28 )

      name   age city
0      NaN   NaN  NaN
1      Bob  30.0   LA
2  Charlie  35.0   SF
3    David  40.0   NY

.mask()----> osite to where() , replace matching values with NAN

In [48]:
df.mask(df['age'] > 28)

    name   age city
0  Alice  25.0   NY
1    NaN   NaN  NaN
2    NaN   NaN  NaN
3    NaN   NaN  NaN

### Adding, Modifying & Dropping Columns/Rows

In [30]:
df2=df.copy()

In [31]:
df2

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [33]:
# Adding a new column from an existing one
df2['senior']=df2['age']
df2

      name  age city  senior
0    Alice   25   NY      25
1      Bob   30   LA      30
2  Charlie   35   SF      35
3    David   40   NY      40

In [34]:
df2['senior']=df2['age'] > 30
df2

      name  age city  senior
0    Alice   25   NY   False
1      Bob   30   LA   False
2  Charlie   35   SF    True
3    David   40   NY    True

In [38]:
#Adding a computed column
df2['age_plus_5']=df2['age']+5
df2

      name  age city  senior  age_plus_5
0    Alice   25   NY      30          30
1      Bob   30   LA      35          35
2  Charlie   35   SF      40          40
3    David   40   NY      45          45

In [40]:
# .rename----> Rename the column
df2.rename(columns={'city':'location'},inplace=True)
df2

      name  age location  senior  age_plus_5
0    Alice   25       NY      30          30
1      Bob   30       LA      35          35
2  Charlie   35       SF      40          40
3    David   40       NY      45          45

In [41]:
# .drop(columns=....)----> Drop a column
df2.drop(columns=['age_plus_5'],inplace=True)
df2

      name  age location  senior
0    Alice   25       NY      30
1      Bob   30       LA      35
2  Charlie   35       SF      40
3    David   40       NY      45

In [42]:
#.drop(index=....)---->drop a row
df2.drop(index=0,inplace=False)

      name  age location  senior
1      Bob   30       LA      35
2  Charlie   35       SF      40
3    David   40       NY      45

In [44]:
# .insert()---> Insert a column at a specific position
df2.insert(1,'id',range(len(df2)))
df2

ValueError: cannot insert id, already exists

In [45]:
df2

      name  id  age location  senior
0    Alice   0   25       NY      30
1      Bob   1   30       LA      35
2  Charlie   2   35       SF      40
3    David   3   40       NY      45

In [46]:
df2.assign(double_age=df2['age'] *2 )

      name  id  age location  senior  double_age
0    Alice   0   25       NY      30          50
1      Bob   1   30       LA      35          60
2  Charlie   2   35       SF      40          70
3    David   3   40       NY      45          80

### Handling Missing Data

In [5]:
df_na=pd.DataFrame({'a':[1,np.nan,3],'b':[np.nan,2,3]})
df_na

     a    b
0  1.0  NaN
1  NaN  2.0
2  3.0  3.0

In [6]:
#  .isna() ---> Boolean mask of missing values
df_na.isna()

       a      b
0  False   True
1   True  False
2  False  False

In [7]:
# .notna() ----> opposite of .isna()
df_na.notna()

       a      b
0   True  False
1  False   True
2   True   True

In [8]:
#df_na.isnull().sum() ---> Count of missing values per columns
df_na.isnull().sum()

a    1
b    1
dtype: int64

In [10]:
# .dropna()-----> Drop rows containing any NaN
df_na.dropna()

     a    b
2  3.0  3.0

In [11]:
# .dropna(axis=1)-----> Drop columns containing any NaN
df_na.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2]

In [12]:
#  .fillna() ---->  fill missing values with constant
df_na.fillna(0)

     a    b
0  1.0  0.0
1  0.0  2.0
2  3.0  3.0

In [13]:
#   .ffill() -----> Forward fill missing values
df_na.ffill()

     a    b
0  1.0  NaN
1  1.0  2.0
2  3.0  3.0

In [14]:
#   .bfill() -----> Backward fill missing values
df_na.bfill()

     a    b
0  1.0  2.0
1  3.0  2.0
2  3.0  3.0

### Sorting And Ranking

In [2]:
df=pd.DataFrame({
    'name':['Alice','Bob','Charlie','David'],
    'age':[25,30,35,40],
    'city':['NY','LA','SF','NY']
})
df

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [16]:
# .sort_values() ----> Arrange the values in ascending order
df.sort_values('age')

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [17]:
df.sort_values(['city','age'],ascending=[True,False])

      name  age city
1      Bob   30   LA
3    David   40   NY
0    Alice   25   NY
2  Charlie   35   SF

In [18]:
# .sort_index() ----> Sort rows by the index
df.sort_index()

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [20]:
# .rank() ----> Rank values within a column
df['age'].rank

<bound method NDFrame.rank of 0    25
1    30
2    35
3    40
Name: age, dtype: int64>

In [21]:
# .nlargest() ----> Top n rows by a column
df.nlargest(2,'age')

      name  age city
3    David   40   NY
2  Charlie   35   SF

In [24]:
# .nsmallest()----> Bottom n rows by a column
df.nsmallest(3,'age')

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF

### Aggregation and Statistics

In [27]:
# .sum() / .mean() / .median() ------> Basic Aggregations
df['age'].sum(), df['age'].mean(), df['age'].median()

(np.int64(130), np.float64(32.5), 32.5)

In [28]:
# .std() / .var() ----> Spread of data
df['age'].std(), df['age'].var()

(6.454972243679028, 41.666666666666664)

In [29]:
# .min() / .max() ----> Smallest and Largest value
df['age'].min(), df['age'].max()

(25, 40)

In [30]:
# .count() ---> Number of not null values
df['age'].count()

np.int64(4)

In [31]:
# .agg()----> Apply a multiple aggregation functions at once
df.agg({'age':['mean','max','min']})

       age
mean  32.5
max   40.0
min   25.0

In [32]:
# .corr() ----->correlation matrix of numeric columns
df.corr(numeric_only=True)

     age
age  1.0

In [33]:
# .mode() ---->Most frequently occuring value
df['city'].mode()

0    NY
Name: city, dtype: object

### GroupBy Operations

In [4]:
g=df.groupby('city')

In [9]:
#  .size()---> Number of rows in each group
g.size()

city
LA    1
NY    2
SF    1
dtype: int64

In [6]:
# Group then aggregate a single column
g['age'].mean()

city
LA    30.0
NY    32.5
SF    35.0
Name: age, dtype: float64

In [8]:
# .agg()---> On a group by -- Multiple aggregations per group

In [10]:
g.agg({'age':['mean','sum']})

       age
      mean sum
city
LA    30.0  30
NY    32.5  65
SF    35.0  35

In [11]:
#  .apply()---> on a groupby -- custom function per group

In [13]:
g.apply(lambda x: x['age'].max() - x['age'].min())

C:\Users\PRIYA\AppData\Local\Temp\ipykernel_1536\1928885914.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  g.apply(lambda x: x['age'].max() - x['age'].min())

city
LA     0
NY    15
SF     0
dtype: int64

In [17]:
add=lambda a,b:a+b

In [18]:
add(2,2)

4

Iterating over groups with a for loop

In [19]:
for name, group in g:
    print(name)
    print(group)

LA
  name  age city
1  Bob   30   LA
NY
    name  age city
0  Alice   25   NY
3  David   40   NY
SF
      name  age city
2  Charlie   35   SF

In [20]:
# .get_group() ---> Retrieve a specific group
g.get_group('NY')

    name  age city
0  Alice   25   NY
3  David   40   NY

In [22]:
#Data

In [23]:
type(df)

pandas.core.frame.DataFrame

In [26]:
#Converting the file from pandas into csv
df.to_csv('data.csv', index=False)

In [25]:
# to import the file 
pd.read_csv('data.csv')

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [27]:
#Converting the file  into json

In [28]:
# .to_json() / pd.read_json() ----> write and read json files

In [29]:
df.to_json('data.json', orient='records')
pd.read_json('data.json')

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [30]:
# .to_excel() / pd.read_excel() ---> Write and read excel files

In [37]:
%pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\priya\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\priya\anaconda3\lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

In [40]:
df

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [45]:
df.to_excel('data.xlsx',index=False)
pd.read_excel('data.xlsx')

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [46]:
# .to_dict()---> Convert dataframe into a list of dictionary

In [47]:
df.to_dict(orient='records')

[{'name': 'Alice', 'age': 25, 'city': 'NY'},
 {'name': 'Bob', 'age': 30, 'city': 'LA'},
 {'name': 'Charlie', 'age': 35, 'city': 'SF'},
 {'name': 'David', 'age': 40, 'city': 'NY'}]

In [48]:
pd.DataFrame.from_dict({'a':[1,2]})

   a
0  1
1  2